name: Simple Workflow

on:
  repository_dispatch:
    types: [trigger-simple-workflow]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Display a Message
        run: echo "Workflow triggered via repository dispatch event!"

      - name: Print Current Directory
        run: pwd

      - name: List Files in Directory
        run: ls -al

      - name: Docker
        run: docker ps || echo "no docker"

      - name: Node
        run: node -v || echo "no docker"
        
      - name: Git
        run: git status
